import 'package:flutter/material.dart';

class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _values = {
    'ar': {
      'settings': 'الإعدادات',
      'language': 'لغة التطبيق',
      'location': 'المدينة',
      'appearance': 'مظهر التطبيق',
      'dark': 'داكن',
      'light': 'فاتح',
      'rateApp': 'تقييم التطبيق',
      'share': 'مشاركة مع الأصدقاء',
      'version': 'منيب - الإصدار 1.0.0',
      'chooseLanguage': 'اختر اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'home': 'الرئيسية',
      'azkar': 'الأذكار',
      'training': 'التدريب',
      'nextPrayer': 'الصلاة القادمة',
      'todayPrayerTimes': 'مواقيت اليوم',
      'changeImsakia': 'تغيير الإمساكية',
      'noPrayerTimes': 'لا توجد أوقات صلاة',
      'uploadOrLocation': 'ارفع إمساكيتك أو دع منيب يجلبها بناءً على موقعك',
      'fetchCityTimes': 'جلب أوقات مدينتي تلقائياً',
      'uploadImsakia': 'رفع صورة الإمساكية',
      'teachMePrayer': 'علّمني الصلاة',
      'coachDescription': 'تعلّم الصلاة خطوة بخطوة مع مدرب ذكي يتابع حركاتك ويساعدك على التحسن.',
      'startTraining': 'ابدأ التدريب',
      'notifications': 'الإشعارات',
      'hello': 'السلام عليكم',
      'locationUnknown': 'الموقع غير محدد',
      'fetchFailed': 'لم نتمكن من جلب الأوقات تلقائياً، يرجى رفع الإمساكية يدوياً',
      'or': 'أو',
      'fajr': 'الفجر',
      'sunrise': 'الشروق',
      'dhuhr': 'الظهر',
      'asr': 'العصر',
      'maghrib': 'المغرب',
      'isha': 'العشاء',
      'profile': 'الملف الشخصي',
      'munibUser': 'مستخدم منيب',
      'email': 'البريد الإلكتروني',
      'accountType': 'نوع الحساب',
      'emailAccount': 'بريد إلكتروني',
      'notAvailable': 'غير متوفر',
      'signOut': 'تسجيل الخروج',
      'signIn': 'تسجيل الدخول',
      'createAccount': 'إنشاء حساب جديد',
      'fullName': 'الاسم الكامل',
      'password': 'كلمة المرور',
      'login': 'دخول',
      'register': 'إنشاء الحساب',
      'googleLogin': 'الدخول بواسطة جوجل',
      'noAccount': 'لا تملك حساباً؟ سجل الآن',
      'haveAccount': 'تملك حساباً بالفعل؟ سجل دخولك',
      'requiredField': 'هذا الحقل مطلوب',
      'invalidCredentials': 'تأكد من بيانات الدخول أو حالة حسابك',
      'googleCancelled': 'تم إلغاء عملية الدخول',
      'googleError': 'حدث خطأ غير متوقع أثناء الاتصال بجوجل',
      'uploadTitle': 'رفع الإمساكية',
      'uploadHint': 'اختر صورة واضحة للإمساكية وسيتولى منيب استخراج المواقيت.',
      'camera': 'التقاط صورة',
      'gallery': 'اختيار من المعرض',
      'file': 'اختيار ملف',
      'processing': 'جاري معالجة الإمساكية',
      'processing1': 'تجهيز الملف',
      'processing2': 'قراءة المحتوى',
      'processing3': 'تنظيم مواقيت الصلاة',
      'processing4': 'إنهاء النتائج',
      'processingError': 'تعذر قراءة الإمساكية. جرّب صورة أوضح أو ملفاً آخر.',
      'tryAgain': 'حاول مرة أخرى',
    },
    'en': {
      'settings': 'Settings',
      'language': 'App Language',
      'location': 'City',
      'appearance': 'Appearance',
      'dark': 'Dark',
      'light': 'Light',
      'rateApp': 'Rate App',
      'share': 'Share with Friends',
      'version': 'Munib - v1.0.0',
      'chooseLanguage': 'Choose Language',
      'arabic': 'العربية',
      'english': 'English',
      'home': 'Home',
      'azkar': 'Adhkar',
      'training': 'Training',
      'nextPrayer': 'Next Prayer',
      'todayPrayerTimes': "Today's Prayer Times",
      'changeImsakia': 'Change Imsakia',
      'noPrayerTimes': 'No prayer times available',
      'uploadOrLocation': 'Upload your Imsakia or let Munib fetch it using your location',
      'fetchCityTimes': 'Fetch my city prayer times',
      'uploadImsakia': 'Upload Imsakia image',
      'teachMePrayer': 'Teach me prayer',
      'coachDescription': 'Learn prayer step by step with a smart coach that follows your movements and helps you improve.',
      'startTraining': 'Start Training',
      'notifications': 'Notifications',
      'hello': 'Assalamu Alaikum',
      'locationUnknown': 'Location not set',
      'fetchFailed': 'We could not fetch prayer times automatically. Please upload your Imsakia manually.',
      'or': 'or',
      'fajr': 'Fajr',
      'sunrise': 'Sunrise',
      'dhuhr': 'Dhuhr',
      'asr': 'Asr',
      'maghrib': 'Maghrib',
      'isha': 'Isha',
      'profile': 'Profile',
      'munibUser': 'Munib User',
      'email': 'Email',
      'accountType': 'Account Type',
      'emailAccount': 'Email',
      'notAvailable': 'Not available',
      'signOut': 'Sign Out',
      'signIn': 'Sign In',
      'createAccount': 'Create Account',
      'fullName': 'Full Name',
      'password': 'Password',
      'login': 'Sign In',
      'register': 'Create Account',
      'googleLogin': 'Continue with Google',
      'noAccount': "Don't have an account? Sign up",
      'haveAccount': 'Already have an account? Sign in',
      'requiredField': 'This field is required',
      'invalidCredentials': 'Check your sign-in details or account status',
      'googleCancelled': 'Sign-in was cancelled',
      'googleError': 'An unexpected error occurred while connecting to Google',
      'uploadTitle': 'Upload Imsakia',
      'uploadHint': 'Choose a clear Imsakia image and Munib will extract the prayer times.',
      'camera': 'Take a photo',
      'gallery': 'Choose from gallery',
      'file': 'Choose a file',
      'processing': 'Processing Imsakia',
      'processing1': 'Preparing file',
      'processing2': 'Reading content',
      'processing3': 'Structuring prayer times',
      'processing4': 'Finalizing results',
      'processingError': 'Could not read this Imsakia. Try a clearer image or another file.',
      'tryAgain': 'Try again',
    },
  };

  static String text(BuildContext context, String key) {
    final code = Localizations.localeOf(context).languageCode == 'en' ? 'en' : 'ar';
    return _values[code]?[key] ?? _values['ar']?[key] ?? key;
  }
}

extension MunibStrings on BuildContext {
  String tr(String key) => AppStrings.text(this, key);
}
