package com.example.munib

data class NafhaContent(
    val kind: String,
    val textAr: String,
    val textEn: String,
    val sourceAr: String,
    val sourceEn: String,
    val detailTitleAr: String,
    val detailTitleEn: String,
    val detailAr: String,
    val detailEn: String,
    val contextTag: String? = null,
)

object NafahatContentRepository {
    /*
     * This library is deliberately bundled as text instead of being fetched at
     * display time. It adds only a small amount to the APK, works offline, and
     * guarantees that a Nafha opens instantly with its source/explanation ready.
     * Religious text is curated here and is never generated at runtime.
     */
    val items: List<NafhaContent> = listOf(
        NafhaContent(
            kind = "آية",
            textAr = "﴿ألا بذكر الله تطمئن القلوب﴾",
            textEn = "Indeed, hearts find rest in the remembrance of Allah.",
            sourceAr = "الرعد: 28",
            sourceEn = "Quran 13:28",
            detailTitleAr = "تفسير مختصر",
            detailTitleEn = "Brief meaning",
            detailAr = "ذكر الله والإقبال عليه من أعظم أسباب سكينة القلب وثباته.",
            detailEn = "Remembering Allah and turning to Him are among the greatest sources of calm and steadiness for the heart.",
        ),
        NafhaContent(
            kind = "آية",
            textAr = "﴿ومن يتوكل على الله فهو حسبه﴾",
            textEn = "Whoever relies upon Allah, He is sufficient for them.",
            sourceAr = "الطلاق: 3",
            sourceEn = "Quran 65:3",
            detailTitleAr = "تفسير مختصر",
            detailTitleEn = "Brief meaning",
            detailAr = "التوكل يجمع صدق الاعتماد على الله مع الأخذ بالأسباب المشروعة.",
            detailEn = "Reliance on Allah combines sincere trust in Him with taking the means available to you.",
        ),
        NafhaContent(
            kind = "آية",
            textAr = "﴿إن مع العسر يسرا﴾",
            textEn = "Indeed, with hardship comes ease.",
            sourceAr = "الشرح: 6",
            sourceEn = "Quran 94:6",
            detailTitleAr = "تفسير مختصر",
            detailTitleEn = "Brief meaning",
            detailAr = "تذكير بأن الشدة لا تدوم وأن الله يجعل مع العسر أبواباً من التيسير.",
            detailEn = "A reminder that hardship does not last and that Allah places avenues of ease alongside difficulty.",
        ),
        NafhaContent(
            kind = "آية",
            textAr = "﴿فاذكروني أذكركم واشكروا لي ولا تكفرون﴾",
            textEn = "Remember Me; I will remember you. Be grateful to Me.",
            sourceAr = "البقرة: 152",
            sourceEn = "Quran 2:152",
            detailTitleAr = "تفسير مختصر",
            detailTitleEn = "Brief meaning",
            detailAr = "في الآية دعوة إلى دوام الذكر والشكر، وفيهما حياة القلب وزيادة الصلة بالله.",
            detailEn = "The verse calls to consistent remembrance and gratitude, both of which strengthen the heart's connection to Allah.",
        ),
        NafhaContent(
            kind = "آية",
            textAr = "﴿إن الصلاة كانت على المؤمنين كتابا موقوتا﴾",
            textEn = "Prayer has been prescribed for believers at appointed times.",
            sourceAr = "النساء: 103",
            sourceEn = "Quran 4:103",
            detailTitleAr = "تذكير بالصلاة",
            detailTitleEn = "Prayer reminder",
            detailAr = "من أعظم المحافظة على الصلاة أداؤها في وقتها وعدم تأخيرها بلا عذر.",
            detailEn = "An essential part of guarding the prayer is performing it within its appointed time.",
            contextTag = "pre_prayer",
        ),
        NafhaContent(
            kind = "آية",
            textAr = "﴿واستعينوا بالصبر والصلاة﴾",
            textEn = "Seek help through patience and prayer.",
            sourceAr = "البقرة: 45",
            sourceEn = "Quran 2:45",
            detailTitleAr = "تفسير مختصر",
            detailTitleEn = "Brief meaning",
            detailAr = "عند الضيق والشدائد يجمع المؤمن بين الصبر واللجوء إلى الله بالصلاة.",
            detailEn = "During difficulty, the believer combines patience with turning to Allah through prayer.",
        ),
        NafhaContent(
            kind = "آية",
            textAr = "﴿يا أيها الذين آمنوا إذا نودي للصلاة من يوم الجمعة فاسعوا إلى ذكر الله﴾",
            textEn = "When the call is made for Friday prayer, proceed to the remembrance of Allah.",
            sourceAr = "الجمعة: 9",
            sourceEn = "Quran 62:9",
            detailTitleAr = "تذكير الجمعة",
            detailTitleEn = "Friday reminder",
            detailAr = "إذا نودي لصلاة الجمعة يترك المسلم ما يشغله ويتوجه إلى الصلاة وذكر الله.",
            detailEn = "When the Friday prayer is called, worldly distractions are set aside for prayer and remembrance.",
            contextTag = "friday",
        ),
        NafhaContent(
            kind = "حديث",
            textAr = "أحب الأعمال إلى الله أدومها وإن قل",
            textEn = "The deeds most beloved to Allah are those done consistently, even if they are small.",
            sourceAr = "متفق عليه",
            sourceEn = "Sahih al-Bukhari and Sahih Muslim",
            detailTitleAr = "الفائدة",
            detailTitleEn = "Benefit",
            detailAr = "العمل القليل المستمر خير من اندفاع كبير ينقطع سريعاً.",
            detailEn = "Small, consistent worship is better than a large burst of effort that quickly stops.",
        ),
        NafhaContent(
            kind = "حديث",
            textAr = "الكلمة الطيبة صدقة",
            textEn = "A good word is charity.",
            sourceAr = "متفق عليه",
            sourceEn = "Sahih al-Bukhari and Sahih Muslim",
            detailTitleAr = "الفائدة",
            detailTitleEn = "Benefit",
            detailAr = "الكلام الحسن والإحسان باللسان باب يومي من أبواب الصدقة.",
            detailEn = "Kind speech is a daily form of charity that costs nothing and benefits others.",
        ),
        NafhaContent(
            kind = "حديث",
            textAr = "كلمتان خفيفتان على اللسان، ثقيلتان في الميزان، حبيبتان إلى الرحمن: سبحان الله وبحمده، سبحان الله العظيم",
            textEn = "Two phrases are light on the tongue, heavy on the scale and beloved to the Most Merciful: Subhan Allah wa bihamdih, Subhan Allah al-Azim.",
            sourceAr = "متفق عليه",
            sourceEn = "Sahih al-Bukhari and Sahih Muslim",
            detailTitleAr = "الفائدة",
            detailTitleEn = "Benefit",
            detailAr = "ذكر يسير يجمع التسبيح والحمد، وجاء في الحديث بيان عظيم فضله.",
            detailEn = "An easy remembrance combining glorification and praise, with great reward described in the hadith.",
        ),
        NafhaContent(
            kind = "حديث",
            textAr = "من صلى علي صلاة صلى الله عليه بها عشرا",
            textEn = "Whoever sends one blessing upon me, Allah sends ten blessings upon them.",
            sourceAr = "رواه مسلم",
            sourceEn = "Sahih Muslim",
            detailTitleAr = "الفائدة",
            detailTitleEn = "Benefit",
            detailAr = "الصلاة على النبي ﷺ من الأذكار العظيمة، ويضاعف الله بها الأجر.",
            detailEn = "Sending blessings upon the Prophet ﷺ is a great remembrance whose reward is multiplied.",
        ),
        NafhaContent(
            kind = "حديث",
            textAr = "لا يزال لسانك رطبا من ذكر الله",
            textEn = "Keep your tongue moist with the remembrance of Allah.",
            sourceAr = "رواه الترمذي",
            sourceEn = "Jami at-Tirmidhi",
            detailTitleAr = "الفائدة",
            detailTitleEn = "Benefit",
            detailAr = "وصية جامعة بالإكثار من الذكر وجعله مصاحباً للإنسان في يومه.",
            detailEn = "A concise instruction to keep remembrance present throughout the day.",
        ),
        NafhaContent(
            kind = "ذكر",
            textAr = "سبحان الله وبحمده",
            textEn = "Subhan Allah wa bihamdih",
            sourceAr = "ذكر ثابت في السنة",
            sourceEn = "Established in the Sunnah",
            detailTitleAr = "من فضائله",
            detailTitleEn = "Virtue",
            detailAr = "ثبت في الصحيح أن من قالها مائة مرة في يوم حطت خطاياه وإن كانت مثل زبد البحر.",
            detailEn = "Authentic hadith describes great forgiveness for saying it one hundred times in a day.",
            contextTag = "morning",
        ),
        NafhaContent(
            kind = "ذكر",
            textAr = "لا حول ولا قوة إلا بالله",
            textEn = "La hawla wa la quwwata illa billah",
            sourceAr = "ذكر ثابت في السنة",
            sourceEn = "Established in the Sunnah",
            detailTitleAr = "من فضائله",
            detailTitleEn = "Virtue",
            detailAr = "وصفها النبي ﷺ بأنها كنز من كنوز الجنة.",
            detailEn = "The Prophet ﷺ described it as a treasure from the treasures of Paradise.",
            contextTag = "evening",
        ),
        NafhaContent(
            kind = "ذكر",
            textAr = "أستغفر الله وأتوب إليه",
            textEn = "Astaghfirullah wa atubu ilayh",
            sourceAr = "ذكر ثابت في السنة",
            sourceEn = "Established in the Sunnah",
            detailTitleAr = "المعنى",
            detailTitleEn = "Meaning",
            detailAr = "استغفار يتضمن طلب المغفرة مع الرجوع إلى الله وتجديد التوبة.",
            detailEn = "It combines asking Allah for forgiveness with returning to Him in repentance.",
        ),
        NafhaContent(
            kind = "ذكر",
            textAr = "سبحان الله، والحمد لله، ولا إله إلا الله، والله أكبر",
            textEn = "Subhan Allah, Alhamdulillah, La ilaha illa Allah, Allahu Akbar",
            sourceAr = "أذكار ثابتة في السنة",
            sourceEn = "Established remembrances in the Sunnah",
            detailTitleAr = "من فضائلها",
            detailTitleEn = "Virtue",
            detailAr = "كلمات جامعة للتسبيح والحمد والتوحيد والتكبير، وهي من أحب الكلام إلى الله.",
            detailEn = "These words combine glorification, praise, tawhid and magnification, and are among the most beloved words to Allah.",
        ),
        NafhaContent(
            kind = "ذكر",
            textAr = "رضيت بالله ربا، وبالإسلام دينا، وبمحمد ﷺ نبيا",
            textEn = "I am pleased with Allah as Lord, Islam as religion, and Muhammad ﷺ as Prophet.",
            sourceAr = "من أذكار الصباح والمساء",
            sourceEn = "Morning and evening remembrance",
            detailTitleAr = "المعنى",
            detailTitleEn = "Meaning",
            detailAr = "تجديد للرضا بالله ودينه ونبيه ﷺ، ويقال في أذكار الصباح والمساء.",
            detailEn = "A renewal of contentment with Allah, His religion and His Prophet ﷺ, recited in morning and evening adhkar.",
            contextTag = "morning",
        ),
        NafhaContent(
            kind = "ذكر",
            textAr = "أعوذ بكلمات الله التامات من شر ما خلق",
            textEn = "I seek refuge in the perfect words of Allah from the evil of what He created.",
            sourceAr = "رواه مسلم",
            sourceEn = "Sahih Muslim",
            detailTitleAr = "من فضائله",
            detailTitleEn = "Virtue",
            detailAr = "ذكر للاستعاذة بالله، ويشرع في المساء وعند النزول بمكان.",
            detailEn = "A remembrance seeking Allah's protection, prescribed in the evening and when stopping at a place.",
            contextTag = "evening",
        ),
        NafhaContent(
            kind = "ذكر",
            textAr = "اللهم صل وسلم على نبينا محمد",
            textEn = "O Allah, send Your peace and blessings upon our Prophet Muhammad.",
            sourceAr = "الصلاة على النبي ﷺ",
            sourceEn = "Sending blessings upon the Prophet ﷺ",
            detailTitleAr = "من فضائلها",
            detailTitleEn = "Virtue",
            detailAr = "ثبت أن من صلى على النبي ﷺ صلاة صلى الله عليه بها عشراً.",
            detailEn = "Authentic hadith states that one blessing upon the Prophet ﷺ is rewarded with ten blessings from Allah.",
        ),
        NafhaContent(
            kind = "أثر طيب",
            textAr = "ابدأ بالقليل الذي تستطيع أن تداوم عليه.",
            textEn = "Start with the small good deed you can actually sustain.",
            sourceAr = "تذكير تربوي",
            sourceEn = "Gentle reminder",
            detailTitleAr = "الفكرة",
            detailTitleEn = "Idea",
            detailAr = "الثبات على عادة صالحة صغيرة يبني أثراً أكبر من خطط كثيرة لا تستمر.",
            detailEn = "A small good habit that lasts can have more impact than ambitious plans that do not continue.",
        ),
        NafhaContent(
            kind = "أثر طيب",
            textAr = "اجعل لك خبيئة من عمل صالح لا يعلم بها أحد.",
            textEn = "Keep a private good deed known only to Allah.",
            sourceAr = "تذكير تربوي",
            sourceEn = "Gentle reminder",
            detailTitleAr = "الفكرة",
            detailTitleEn = "Idea",
            detailAr = "إخفاء بعض الطاعات يعين على الإخلاص ويجعل للعبد عملاً بينه وبين ربه.",
            detailEn = "Keeping some worship private can strengthen sincerity and preserve deeds done only for Allah.",
        ),
        NafhaContent(
            kind = "أثر طيب",
            textAr = "لا تنتظر مزاجاً مثالياً للطاعة؛ ابدأ بما تستطيع الآن.",
            textEn = "Do not wait for the perfect mood to worship; begin with what you can do now.",
            sourceAr = "تذكير تربوي",
            sourceEn = "Gentle reminder",
            detailTitleAr = "الفكرة",
            detailTitleEn = "Idea",
            detailAr = "الاستمرار يتكون من خطوات صغيرة متكررة، لا من انتظار اللحظة المثالية.",
            detailEn = "Consistency grows from repeated small steps, not from waiting for a perfect moment.",
        ),
        NafhaContent(
            kind = "أثر طيب",
            textAr = "إذا أثقلتك الدنيا فاجعل الصلاة محطة عودة لا مهمة إضافية.",
            textEn = "When life feels heavy, let prayer be a place to return to, not another task on the list.",
            sourceAr = "تذكير تربوي",
            sourceEn = "Gentle reminder",
            detailTitleAr = "الفكرة",
            detailTitleEn = "Idea",
            detailAr = "الصلاة صلة بالله وسكينة للقلب، وليست مجرد بند ينجز بسرعة.",
            detailEn = "Prayer is a connection with Allah and rest for the heart, not merely an item to finish quickly.",
            contextTag = "pre_prayer",
        ),
    )
}
